# Generated by Django 5.2 on 2025-05-16 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Categories", "0001_initial"),
        ("News", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Articles",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("summary", models.TextField(blank=True, null=True)),
                ("url", models.URLField()),
                ("published_at", models.DateTimeField()),
                ("language", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="Categories.categories",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="News.news",
                    ),
                ),
            ],
        ),
    ]
