# Generated by Django 5.2 on 2025-05-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("News", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="logo_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="url",
            field=models.URLField(max_length=500),
        ),
    ]
