# Generated by Django 5.2 on 2025-05-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="profiles/default.jpg", upload_to="uploads/"
            ),
        ),
    ]
